\AtEndDocument{\ifx\hyper@anchor\@undefined
\HyPL@Entry{0<</S/D>>}
\HyperFirstAtBeginDocument{\ifx\hyper@anchor\@undefined
\fi}
\fi}
\gdef\HyperFirstAtBeginDocument#1{#1}
\gdef\contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\global\let\hyper@last\relax 
\global\let\oldcontentsline\contentsline
\global\let\oldnewlabel\newlabel
\let\contentsline\oldcontentsline
\let\newlabel\oldnewlabel
\providecommand*\HyPL@Entry[1]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\xdef\lastpage@lastpageHy{2}
\xdef\lastpage@lastpage{2}
